package es.medac.MascotaApp.vistas;

import es.medac.MascotaApp.controller.ConexionBD;
import es.medac.MascotaApp.controller.Consultas;
import es.medac.MascotaApp.model.Clientes;
import es.medac.MascotaApp.model.Mascotas;
import es.medac.MascotaApp.model.Pesos;
import es.medac.MascotaApp.model.Vacunas;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class consultaEspMascota extends javax.swing.JFrame {
private Connection conexionBD;
    /**
     * Creates new form consultaEspMascota
     */
    public consultaEspMascota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idMascotaConsultaEsp = new javax.swing.JTextField();
        jIdMascota = new javax.swing.JLabel();
        jbMenu = new javax.swing.JButton();
        jTituloConsultasEspecif = new javax.swing.JLabel();
        jbSalir = new javax.swing.JButton();
        consultaMascEscp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoMascota = new javax.swing.JTextArea();
        jbConsultarCliente = new javax.swing.JButton();
        idClienteConsultaEsp = new javax.swing.JTextField();
        jIdCliente = new javax.swing.JLabel();
        jFondoConsultaEspecifica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idMascotaConsultaEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMascotaConsultaEspActionPerformed(evt);
            }
        });
        getContentPane().add(idMascotaConsultaEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 70, -1));

        jIdMascota.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jIdMascota.setText("ID MASCOTA");
        getContentPane().add(jIdMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jbMenu.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jbMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img's/icons8-cerrar-sesión-60.png"))); // NOI18N
        jbMenu.setText("MENU");
        jbMenu.setContentAreaFilled(false);
        jbMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        jTituloConsultasEspecif.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jTituloConsultasEspecif.setForeground(new java.awt.Color(0, 153, 153));
        jTituloConsultasEspecif.setText("CONSULTAS ESPECIFICAS");
        getContentPane().add(jTituloConsultasEspecif, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jbSalir.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img's/icons8-cerrar-sesión-60.png"))); // NOI18N
        jbSalir.setText("SALIR");
        jbSalir.setContentAreaFilled(false);
        jbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        consultaMascEscp.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        consultaMascEscp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img's/icons8-abajo-60.png"))); // NOI18N
        consultaMascEscp.setText("CONSULTAR MASCOTA");
        consultaMascEscp.setContentAreaFilled(false);
        consultaMascEscp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultaMascEscp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaMascEscpActionPerformed(evt);
            }
        });
        getContentPane().add(consultaMascEscp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 70));

        infoMascota.setColumns(20);
        infoMascota.setRows(5);
        jScrollPane1.setViewportView(infoMascota);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 390, 260));

        jbConsultarCliente.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jbConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img's/icons8-abajo-60.png"))); // NOI18N
        jbConsultarCliente.setText("CONSULTAR CLIENTE");
        jbConsultarCliente.setContentAreaFilled(false);
        jbConsultarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jbConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, 50));
        getContentPane().add(idClienteConsultaEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 80, -1));

        jIdCliente.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jIdCliente.setText("ID CLIENTE");
        getContentPane().add(jIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 90, -1));

        jFondoConsultaEspecifica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img's/perroTablet.png"))); // NOI18N
        getContentPane().add(jFondoConsultaEspecifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Boton que regresa a la interfaz Menu
     * @param evt 
     */
    private void jbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuActionPerformed
        // TODO add your handling code here:
        setVisible (false);
        Menu m1 = new Menu();
        m1.setVisible(true);
    }//GEN-LAST:event_jbMenuActionPerformed
    /**
     * Boton que cierra el programa
     * @param evt 
     */
    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed
    /**
     * Boton que realiza la consulta especifica de una mascota tomando el id que se le paso en el jTextField y utilizando el metodo
     * de la clase Consultas para realizar las consultas necesarias y luego creando instancias de las clases necesarias asignando los
     * valores obtenidos en los constructores para luego asignarles el valor en un jTextArea de estos objetos con el toString
     * @param evt 
     */
    private void consultaMascEscpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaMascEscpActionPerformed
        // TODO add your handling code here:     
        //infoConsultaEsp(Integer.parseInt(idMascotaConsultaEsp.getText()));
        int id = Integer.parseInt(idMascotaConsultaEsp.getText());
        Consultas c1 = new Consultas();
        Object dato[];
        Object dato1 [] = c1.cVacunasPorId(id);
        Object dato2 [] = c1.cPesoPorId(id);
    try {
        dato = infoMasc(id);
        Mascotas m1 = new Mascotas(id,(int)dato[0], (String)dato[1], (String)dato[2], (String)dato[3], (String)dato[4], (Date)dato[5], (int)dato[6]);
        Vacunas v1 = new Vacunas((Date)dato1[0], (String)dato1[1],(Date)dato1[2]);
        Pesos p1 = new Pesos((Date)dato2[0], (Double)dato2[1]);
        infoMascota.setText(m1.toString()+v1.toString()+p1.toString());
        
    } catch (SQLException ex) {
        Logger.getLogger(consultaEspMascota.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_consultaMascEscpActionPerformed

    private void idMascotaConsultaEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMascotaConsultaEspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idMascotaConsultaEspActionPerformed
    /**
     * Similar al de la consulta por masocta tomando un id de cliente y retornando los datos del cliente con el id escrito
     * en el jTextField y creando una clase Clientes y al constructor asignandole los datos obtenidos con los metodos de las clases
     * consultas para luego agregarlos a un textArea usando el toString de la clase
     * @param evt 
     */
    private void jbConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarClienteActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(idClienteConsultaEsp.getText());
        Consultas c1 = new Consultas();
        Object dato [] = c1.clienteById(id);
        try{
            dato = infoCliente(id);
            Clientes cl = new Clientes(id, (String)dato[0], (String)dato[1], (int)dato[2]);
            infoMascota.setText(cl.info());
        } catch (SQLException ex) {
        Logger.getLogger(consultaEspMascota.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jbConsultarClienteActionPerformed

    private Object [] infoMasc(int id) throws SQLException{
       Object [] dato = new Object[7];
       String sql = "SELECT * FROM mascotas where idMascota = ?;"; 
       conexionBD = new ConexionBD().getConexion();
       PreparedStatement st = conexionBD.prepareStatement(sql);
       st.setInt(1, id);  
       ResultSet rs = st.executeQuery();
       while(rs.next()){
           dato[0] = rs.getInt("idCliente");
           dato[1] = rs.getString("aliasMascota");
           dato[2] = rs.getString("especie");
           dato[3] = rs.getString("raza");
           dato[4] = rs.getString("colorPelo");
           dato[5] = rs.getDate("fechaNacimiento");
           dato[6] = rs.getInt("vacunaciones");        
       }
       conexionBD.close();
       st.close();
       return dato;
    }
    
    private Object [] infoCliente(int id) throws SQLException{
        Object [] dato = new Object[3];
       String sql = "SELECT * FROM clientes where idCliente = ?;"; 
       conexionBD = new ConexionBD().getConexion();
       PreparedStatement st = conexionBD.prepareStatement(sql);
       st.setInt(1, id);  
       ResultSet rs = st.executeQuery();
       while(rs.next()){
           dato[0] = rs.getString("primerApellido");
           dato[1] = rs.getString("cuentaBanco");
           dato[2] = rs.getInt("telefono");      
       }
       conexionBD.close();
       st.close();
       return dato;
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultaEspMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultaEspMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultaEspMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultaEspMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultaEspMascota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultaMascEscp;
    private javax.swing.JTextField idClienteConsultaEsp;
    private javax.swing.JTextField idMascotaConsultaEsp;
    private javax.swing.JTextArea infoMascota;
    private javax.swing.JLabel jFondoConsultaEspecifica;
    private javax.swing.JLabel jIdCliente;
    private javax.swing.JLabel jIdMascota;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTituloConsultasEspecif;
    private javax.swing.JButton jbConsultarCliente;
    private javax.swing.JButton jbMenu;
    private javax.swing.JButton jbSalir;
    // End of variables declaration//GEN-END:variables
}
