/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.MascotaApp.vistas;

import es.medac.MascotaApp.controller.DMLClientes;
import es.medac.MascotaApp.controller.DMLMascotas;
import es.medac.MascotaApp.controller.DMLPesos;
import es.medac.MascotaApp.controller.DMLVacunas;
import es.medac.MascotaApp.controller.InsertarFichero;
import es.medac.MascotaApp.vistas.Menu;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Usuario
 */
public class InsertarMascota extends javax.swing.JFrame {

    /**
     * Creates new form InsertarMascota
     */
    public InsertarMascota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idMascotaInsert = new javax.swing.JTextField();
        idClienteInsert = new javax.swing.JTextField();
        especieInsert = new javax.swing.JTextField();
        pesoInsert = new javax.swing.JTextField();
        razaInsert = new javax.swing.JTextField();
        aliasInsert = new javax.swing.JTextField();
        vacunasInsert = new javax.swing.JTextField();
        peloInsert = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        insertarMascota = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        enfermedadInsert = new javax.swing.JTextField();
        fechaNacimientoInsert = new com.toedter.calendar.JDateChooser();
        fechaPesadoInsert = new com.toedter.calendar.JDateChooser();
        fecha1VacunaInsert = new com.toedter.calendar.JDateChooser();
        fechaProximaInsert = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        insertarxFichero = new javax.swing.JButton();
        registrarCliente = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idMascotaInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMascotaInsertActionPerformed(evt);
            }
        });
        getContentPane().add(idMascotaInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 110, -1));

        idClienteInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idClienteInsertActionPerformed(evt);
            }
        });
        getContentPane().add(idClienteInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 110, -1));

        especieInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especieInsertActionPerformed(evt);
            }
        });
        getContentPane().add(especieInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 110, -1));

        pesoInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoInsertActionPerformed(evt);
            }
        });
        getContentPane().add(pesoInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 110, -1));
        getContentPane().add(razaInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 110, -1));
        getContentPane().add(aliasInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 110, -1));
        getContentPane().add(vacunasInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 110, -1));
        getContentPane().add(peloInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 110, -1));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID MASCOTA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID CLIENTE:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ALIAS MASCOTA:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ESPECIE:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RAZA:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("COLOR DE PELO:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha De Pesado:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, 20));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("VACUNACIONES:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("PESO:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        insertarMascota.setBackground(new java.awt.Color(51, 0, 51));
        insertarMascota.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        insertarMascota.setForeground(new java.awt.Color(255, 255, 255));
        insertarMascota.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\icons8-insertar-80.png")); // NOI18N
        insertarMascota.setText("INSERTAR MASCOTA");
        insertarMascota.setContentAreaFilled(false);
        insertarMascota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarMascotaActionPerformed(evt);
            }
        });
        getContentPane().add(insertarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 280, 60));

        jLabel12.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("FECHA DE NACIMIENTO:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, 20));

        jLabel13.setBackground(new java.awt.Color(204, 204, 255));
        jLabel13.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Fecha Ultima Vacuna:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Enfermedad:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        enfermedadInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfermedadInsertActionPerformed(evt);
            }
        });
        getContentPane().add(enfermedadInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 110, -1));
        getContentPane().add(fechaNacimientoInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 110, -1));
        getContentPane().add(fechaPesadoInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 110, -1));
        getContentPane().add(fecha1VacunaInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 110, -1));
        getContentPane().add(fechaProximaInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 110, -1));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha proxima:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\icons8-cerrar-sesión-60.png")); // NOI18N
        jButton1.setText("VOLVER AL MENU");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, -1, 60));

        jButton2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\icons8-cerrar-sesión-60.png")); // NOI18N
        jButton2.setText("SALIR");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, 60));

        insertarxFichero.setBackground(new java.awt.Color(51, 0, 51));
        insertarxFichero.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        insertarxFichero.setForeground(new java.awt.Color(255, 255, 255));
        insertarxFichero.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\icons8-insertar-80.png")); // NOI18N
        insertarxFichero.setText("INSERTAR MASCOTA POR FICHERO");
        insertarxFichero.setContentAreaFilled(false);
        insertarxFichero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertarxFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarxFicheroActionPerformed(evt);
            }
        });
        getContentPane().add(insertarxFichero, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, 60));

        registrarCliente.setBackground(new java.awt.Color(51, 0, 51));
        registrarCliente.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        registrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        registrarCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\icons8-registro-80.png")); // NOI18N
        registrarCliente.setText("REGISTRAR CLIENTE");
        registrarCliente.setContentAreaFilled(false);
        registrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(registrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 280, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\macka-i-pas.jpg")); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idMascotaInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMascotaInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idMascotaInsertActionPerformed

    private void especieInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especieInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especieInsertActionPerformed

    private void pesoInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoInsertActionPerformed

    private void idClienteInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idClienteInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idClienteInsertActionPerformed

    private void enfermedadInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfermedadInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enfermedadInsertActionPerformed

    /**
     * 
     * @param evt 
     */
    private void insertarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarMascotaActionPerformed
        // TODO add your handling code here:
        int confirm = 1;
        DMLMascotas dm = new DMLMascotas();
        DMLPesos dm1 = new DMLPesos();
        DMLVacunas dm2 = new DMLVacunas();
        long FN = fechaNacimientoInsert.getDate().getTime();
            java.sql.Date sqlFecha = new java.sql.Date(FN);
        long fp = fechaPesadoInsert.getDate().getTime();
            java.sql.Date sqlFecha1 = new java.sql.Date(fp);
        long fv = fecha1VacunaInsert.getDate().getTime();
            java.sql.Date sqlFecha2 = new java.sql.Date(fv);
        long fvp = fechaProximaInsert.getDate().getTime();
            java.sql.Date sqlFecha3 = new java.sql.Date(fvp);
        if(confirm == 1){
            dm.insertAll(Integer.parseInt(idMascotaInsert.getText()), Integer.parseInt(idClienteInsert.getText()), 
                aliasInsert.getText(), especieInsert.getText(), razaInsert.getText(), peloInsert.getText(), sqlFecha, Integer.parseInt(vacunasInsert.getText()));
            confirm++;
            if(confirm == 2){
                dm1.insertAll(Integer.parseInt(idMascotaInsert.getText()), sqlFecha1, Double.parseDouble(pesoInsert.getText()));
                confirm++;
                if(confirm == 3){
                    dm2.insertAll(Integer.parseInt(idMascotaInsert.getText()), sqlFecha2, enfermedadInsert.getText(), sqlFecha3);
                    confirm++;
                    if(confirm == 4){
                        JOptionPane.showMessageDialog(this, "Insersion exitosa");
                    }else{
                        JOptionPane.showMessageDialog(this, "Insersion fallida");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Insersion fallida");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Insersion fallida");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Insersion fallida");
        }
        
    }//GEN-LAST:event_insertarMascotaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible (false);
        Menu m1 = new Menu();
        m1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void registrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarClienteActionPerformed
        // TODO add your handling code here:
        setVisible (false);
        RegistrarCliente r1 = new RegistrarCliente();
        r1.setVisible(true);
    }//GEN-LAST:event_registrarClienteActionPerformed

    private void insertarxFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarxFicheroActionPerformed
        // TODO add your handling code here:
        InsertarFichero iFichero = new InsertarFichero();
        JFileChooser jFileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("TXT & CSV", "txt", "csv");
        jFileChooser.setFileFilter(filtro);
        int respuesta = jFileChooser.showOpenDialog(this);
        if(respuesta == JFileChooser.APPROVE_OPTION){
            String ruta = jFileChooser.getSelectedFile().getPath();
            iFichero.insertarArchivoM(ruta);
        }else{
            JOptionPane.showMessageDialog(this, "Cancelado // Archivo Incorrecto", "", JOptionPane.ERROR_MESSAGE);
        }
    

    }//GEN-LAST:event_insertarxFicheroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarMascota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aliasInsert;
    private javax.swing.JTextField enfermedadInsert;
    private javax.swing.JTextField especieInsert;
    private com.toedter.calendar.JDateChooser fecha1VacunaInsert;
    private com.toedter.calendar.JDateChooser fechaNacimientoInsert;
    private com.toedter.calendar.JDateChooser fechaPesadoInsert;
    private com.toedter.calendar.JDateChooser fechaProximaInsert;
    private javax.swing.JTextField idClienteInsert;
    private javax.swing.JTextField idMascotaInsert;
    private javax.swing.JButton insertarMascota;
    private javax.swing.JButton insertarxFichero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField peloInsert;
    private javax.swing.JTextField pesoInsert;
    private javax.swing.JTextField razaInsert;
    private javax.swing.JButton registrarCliente;
    private javax.swing.JTextField vacunasInsert;
    // End of variables declaration//GEN-END:variables
}
