/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.MascotaApp.vistas;

import es.medac.MascotaApp.controller.DMLMascotas;
import es.medac.MascotaApp.controller.DMLPesos;
import es.medac.MascotaApp.controller.DMLVacunas;
import es.medac.MascotaApp.controller.InsertarFichero;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Usuario
 */
public class InsertarMascota extends javax.swing.JFrame {

    /**
     * Creates new form InsertarMascota
     */
    public InsertarMascota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idMascotaInsert = new javax.swing.JTextField();
        idClienteInsert = new javax.swing.JTextField();
        especieInsert = new javax.swing.JTextField();
        pesoInsert = new javax.swing.JTextField();
        razaInsert = new javax.swing.JTextField();
        aliasInsert = new javax.swing.JTextField();
        vacunasInsert = new javax.swing.JTextField();
        peloInsert = new javax.swing.JTextField();
        jIdMascota = new javax.swing.JLabel();
        jIdCliente = new javax.swing.JLabel();
        jAliasMascota = new javax.swing.JLabel();
        jEspecie = new javax.swing.JLabel();
        jRaza = new javax.swing.JLabel();
        jColorPelo = new javax.swing.JLabel();
        jFechaPesado = new javax.swing.JLabel();
        jVacunaciones = new javax.swing.JLabel();
        jPeso = new javax.swing.JLabel();
        insertarMascota = new javax.swing.JButton();
        jFechaNacimiento = new javax.swing.JLabel();
        jFechaUltVacuna = new javax.swing.JLabel();
        jEnfermedad = new javax.swing.JLabel();
        enfermedadInsert = new javax.swing.JTextField();
        fechaNacimientoInsert = new com.toedter.calendar.JDateChooser();
        fechaPesadoInsert = new com.toedter.calendar.JDateChooser();
        fecha1VacunaInsert = new com.toedter.calendar.JDateChooser();
        fechaProximaInsert = new com.toedter.calendar.JDateChooser();
        jFechaProxima = new javax.swing.JLabel();
        jbMenu = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        insertarxFichero = new javax.swing.JButton();
        registrarCliente = new javax.swing.JButton();
        jFondoInsertarM = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idMascotaInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMascotaInsertActionPerformed(evt);
            }
        });
        getContentPane().add(idMascotaInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 110, -1));

        idClienteInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idClienteInsertActionPerformed(evt);
            }
        });
        getContentPane().add(idClienteInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 110, -1));

        especieInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especieInsertActionPerformed(evt);
            }
        });
        getContentPane().add(especieInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 110, -1));

        pesoInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoInsertActionPerformed(evt);
            }
        });
        getContentPane().add(pesoInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 110, -1));
        getContentPane().add(razaInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 110, -1));
        getContentPane().add(aliasInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 110, -1));
        getContentPane().add(vacunasInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 110, -1));
        getContentPane().add(peloInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 110, -1));

        jIdMascota.setBackground(new java.awt.Color(153, 153, 153));
        jIdMascota.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jIdMascota.setForeground(new java.awt.Color(255, 255, 255));
        jIdMascota.setText("ID MASCOTA:");
        getContentPane().add(jIdMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 20));

        jIdCliente.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jIdCliente.setForeground(new java.awt.Color(255, 255, 255));
        jIdCliente.setText("ID CLIENTE:");
        getContentPane().add(jIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jAliasMascota.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jAliasMascota.setForeground(new java.awt.Color(255, 255, 255));
        jAliasMascota.setText("ALIAS MASCOTA:");
        getContentPane().add(jAliasMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jEspecie.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jEspecie.setForeground(new java.awt.Color(255, 255, 255));
        jEspecie.setText("ESPECIE:");
        getContentPane().add(jEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jRaza.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jRaza.setForeground(new java.awt.Color(255, 255, 255));
        jRaza.setText("RAZA:");
        getContentPane().add(jRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jColorPelo.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jColorPelo.setForeground(new java.awt.Color(255, 255, 255));
        jColorPelo.setText("COLOR DE PELO:");
        getContentPane().add(jColorPelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jFechaPesado.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jFechaPesado.setForeground(new java.awt.Color(255, 255, 255));
        jFechaPesado.setText("FECHA DE PESADO:");
        getContentPane().add(jFechaPesado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, 20));

        jVacunaciones.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jVacunaciones.setForeground(new java.awt.Color(255, 255, 255));
        jVacunaciones.setText("VACUNACIONES:");
        getContentPane().add(jVacunaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jPeso.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jPeso.setForeground(new java.awt.Color(255, 255, 255));
        jPeso.setText("PESO:");
        getContentPane().add(jPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        insertarMascota.setBackground(new java.awt.Color(51, 0, 51));
        insertarMascota.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        insertarMascota.setForeground(new java.awt.Color(255, 255, 255));
        insertarMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img's/icons8-insertar-80.png"))); // NOI18N
        insertarMascota.setText("INSERTAR MASCOTA");
        insertarMascota.setContentAreaFilled(false);
        insertarMascota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarMascotaActionPerformed(evt);
            }
        });
        getContentPane().add(insertarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 280, 60));

        jFechaNacimiento.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jFechaNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        jFechaNacimiento.setText("FECHA DE NACIMIENTO:");
        getContentPane().add(jFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, 20));

        jFechaUltVacuna.setBackground(new java.awt.Color(204, 204, 255));
        jFechaUltVacuna.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jFechaUltVacuna.setForeground(new java.awt.Color(255, 255, 255));
        jFechaUltVacuna.setText("FECHA ULTIMA VACUNA:");
        getContentPane().add(jFechaUltVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jEnfermedad.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jEnfermedad.setForeground(new java.awt.Color(255, 255, 255));
        jEnfermedad.setText("ENFERMEDAD:");
        getContentPane().add(jEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        enfermedadInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfermedadInsertActionPerformed(evt);
            }
        });
        getContentPane().add(enfermedadInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 110, -1));
        getContentPane().add(fechaNacimientoInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 110, -1));
        getContentPane().add(fechaPesadoInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 110, -1));
        getContentPane().add(fecha1VacunaInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 110, -1));
        getContentPane().add(fechaProximaInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 110, -1));

        jFechaProxima.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jFechaProxima.setForeground(new java.awt.Color(255, 255, 255));
        jFechaProxima.setText("FECHA PROXIMA:");
        getContentPane().add(jFechaProxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        jbMenu.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jbMenu.setForeground(new java.awt.Color(255, 255, 255));
        jbMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img's/icons8-cerrar-sesión-60.png"))); // NOI18N
        jbMenu.setText("VOLVER AL MENU");
        jbMenu.setContentAreaFilled(false);
        jbMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, -1, 60));

        jbSalir.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img's/icons8-cerrar-sesión-60.png"))); // NOI18N
        jbSalir.setText("SALIR");
        jbSalir.setContentAreaFilled(false);
        jbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, 60));

        insertarxFichero.setBackground(new java.awt.Color(51, 0, 51));
        insertarxFichero.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        insertarxFichero.setForeground(new java.awt.Color(255, 255, 255));
        insertarxFichero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img's/icons8-insertar-80.png"))); // NOI18N
        insertarxFichero.setText("INSERTAR MASCOTA POR FICHERO");
        insertarxFichero.setContentAreaFilled(false);
        insertarxFichero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertarxFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarxFicheroActionPerformed(evt);
            }
        });
        getContentPane().add(insertarxFichero, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, 60));

        registrarCliente.setBackground(new java.awt.Color(51, 0, 51));
        registrarCliente.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        registrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        registrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img's/icons8-registro-80.png"))); // NOI18N
        registrarCliente.setText("REGISTRAR CLIENTE");
        registrarCliente.setContentAreaFilled(false);
        registrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(registrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 280, 60));

        jFondoInsertarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img's/macka-i-pas.jpg"))); // NOI18N
        getContentPane().add(jFondoInsertarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idMascotaInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMascotaInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idMascotaInsertActionPerformed

    private void especieInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especieInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especieInsertActionPerformed

    private void pesoInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoInsertActionPerformed

    private void idClienteInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idClienteInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idClienteInsertActionPerformed

    private void enfermedadInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfermedadInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enfermedadInsertActionPerformed

    /**
     * Este boton se encarga de realizar todo el proceso de insercción de datos usando los metodos de las
     * respectivas clases DMLMascotas-Pesos-Vacunas, creando variables de tipo Date para la insercciòn de datos usando
     * los componentes de la libreria JCalendar importada previamente y pasando por filtros para irle confirmando al usuario
     * que todas las insercciones fueron correctas
     * @param evt 
     */
    private void insertarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarMascotaActionPerformed
        // TODO add your handling code here:
        int confirm = 1;
        DMLMascotas dm = new DMLMascotas();
        DMLPesos dm1 = new DMLPesos();
        DMLVacunas dm2 = new DMLVacunas();
        long FN = fechaNacimientoInsert.getDate().getTime();
            java.sql.Date sqlFecha = new java.sql.Date(FN);
        long fp = fechaPesadoInsert.getDate().getTime();
            java.sql.Date sqlFecha1 = new java.sql.Date(fp);
        long fv = fecha1VacunaInsert.getDate().getTime();
            java.sql.Date sqlFecha2 = new java.sql.Date(fv);
        long fvp = fechaProximaInsert.getDate().getTime();
            java.sql.Date sqlFecha3 = new java.sql.Date(fvp);
        if(confirm == 1){
            dm.insertAll(Integer.parseInt(idMascotaInsert.getText()), Integer.parseInt(idClienteInsert.getText()), 
                aliasInsert.getText(), especieInsert.getText(), razaInsert.getText(), peloInsert.getText(), sqlFecha, Integer.parseInt(vacunasInsert.getText()));
            confirm++;
            if(confirm == 2){
                dm1.insertAll(Integer.parseInt(idMascotaInsert.getText()), sqlFecha1, Double.parseDouble(pesoInsert.getText()));
                confirm++;
                if(confirm == 3){
                    dm2.insertAll(Integer.parseInt(idMascotaInsert.getText()), sqlFecha2, enfermedadInsert.getText(), sqlFecha3);
                    confirm++;
                    if(confirm == 4){
                        JOptionPane.showMessageDialog(this, "Insersion exitosa");
                    }else{
                        JOptionPane.showMessageDialog(this, "Insersion fallida");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Insersion fallida");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Insersion fallida");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Insersion fallida");
        }
        
    }//GEN-LAST:event_insertarMascotaActionPerformed
    /**
     * Boton que permitira acceder de nuevo al menu del programa
     * @param evt 
     */
    private void jbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuActionPerformed
        // TODO add your handling code here:
        setVisible (false);
        Menu m1 = new Menu();
        m1.setVisible(true);
    }//GEN-LAST:event_jbMenuActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed
    /**
     * Boton que permitira ingresar a la interfaz para registrar un cliente
     * @param evt 
     */
    private void registrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarClienteActionPerformed
        // TODO add your handling code here:
        setVisible (false);
        RegistrarCliente r1 = new RegistrarCliente();
        r1.setVisible(true);
    }//GEN-LAST:event_registrarClienteActionPerformed
/**
 * Boton que abrira una ventana emergente que nos permitira elegir un archivo de nuestro equipo, contando con filtros para permitir solo
 * archivos txt y csv, una vez ingresado este iniciara el proceso para insertar los datos de este archivo en la BD usando el metodo insertar
 * ArchivoM con la ruta especificada de la clase InsertarFichero
 * @param evt 
 */
    private void insertarxFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarxFicheroActionPerformed
        // TODO add your handling code here:
        InsertarFichero iFichero = new InsertarFichero();
        JFileChooser jFileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("TXT & CSV", "txt", "csv");
        jFileChooser.setFileFilter(filtro);
        int respuesta = jFileChooser.showOpenDialog(this);
        if(respuesta == JFileChooser.APPROVE_OPTION){
            String ruta = jFileChooser.getSelectedFile().getPath();
            iFichero.insertarArchivoM(ruta);
        }else{
            JOptionPane.showMessageDialog(this, "Cancelado // Archivo Incorrecto", "", JOptionPane.ERROR_MESSAGE);
        }
    

    }//GEN-LAST:event_insertarxFicheroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarMascota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aliasInsert;
    private javax.swing.JTextField enfermedadInsert;
    private javax.swing.JTextField especieInsert;
    private com.toedter.calendar.JDateChooser fecha1VacunaInsert;
    private com.toedter.calendar.JDateChooser fechaNacimientoInsert;
    private com.toedter.calendar.JDateChooser fechaPesadoInsert;
    private com.toedter.calendar.JDateChooser fechaProximaInsert;
    private javax.swing.JTextField idClienteInsert;
    private javax.swing.JTextField idMascotaInsert;
    private javax.swing.JButton insertarMascota;
    private javax.swing.JButton insertarxFichero;
    private javax.swing.JLabel jAliasMascota;
    private javax.swing.JLabel jColorPelo;
    private javax.swing.JLabel jEnfermedad;
    private javax.swing.JLabel jEspecie;
    private javax.swing.JLabel jFechaNacimiento;
    private javax.swing.JLabel jFechaPesado;
    private javax.swing.JLabel jFechaProxima;
    private javax.swing.JLabel jFechaUltVacuna;
    private javax.swing.JLabel jFondoInsertarM;
    private javax.swing.JLabel jIdCliente;
    private javax.swing.JLabel jIdMascota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jPeso;
    private javax.swing.JLabel jRaza;
    private javax.swing.JLabel jVacunaciones;
    private javax.swing.JButton jbMenu;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTextField peloInsert;
    private javax.swing.JTextField pesoInsert;
    private javax.swing.JTextField razaInsert;
    private javax.swing.JButton registrarCliente;
    private javax.swing.JTextField vacunasInsert;
    // End of variables declaration//GEN-END:variables
}
