/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.MascotaApp.vistas;
import es.medac.MascotaApp.model.Mascotas;
import es.medac.MascotaApp.model.Pesos;
import es.medac.MascotaApp.model.Vacunas;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuConquistar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        InsertarMascota = new javax.swing.JButton();
        ModificarMascota = new javax.swing.JButton();
        EliminarMascota = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        MascotaEspecifica = new javax.swing.JButton();
        topMascotasPesadas = new javax.swing.JToggleButton();
        topMascotasVacunadas = new javax.swing.JButton();
        menuCerrarSesion = new javax.swing.JButton();
        menuSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoMenu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(897, 551));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuConquistar.setText("CONSULTAR ");
        menuConquistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConquistarActionPerformed(evt);
            }
        });
        getContentPane().add(menuConquistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 110, 30));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("INFORMACION ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 290, 30));

        InsertarMascota.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        InsertarMascota.setForeground(new java.awt.Color(0, 102, 102));
        InsertarMascota.setText("Insertar mascota");
        InsertarMascota.setBorder(null);
        InsertarMascota.setBorderPainted(false);
        InsertarMascota.setContentAreaFilled(false);
        InsertarMascota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InsertarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarMascotaActionPerformed(evt);
            }
        });
        getContentPane().add(InsertarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 210, 60));

        ModificarMascota.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        ModificarMascota.setForeground(new java.awt.Color(0, 102, 102));
        ModificarMascota.setText("Modificar mascota");
        ModificarMascota.setContentAreaFilled(false);
        ModificarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarMascotaActionPerformed(evt);
            }
        });
        getContentPane().add(ModificarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 220, 60));

        EliminarMascota.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        EliminarMascota.setForeground(new java.awt.Color(0, 102, 102));
        EliminarMascota.setText("Eliminar mascota");
        EliminarMascota.setContentAreaFilled(false);
        EliminarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarMascotaActionPerformed(evt);
            }
        });
        getContentPane().add(EliminarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 210, 60));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("MAS OPCIONES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 130, 30));

        MascotaEspecifica.setText("Consulta especifica");
        MascotaEspecifica.setContentAreaFilled(false);
        MascotaEspecifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MascotaEspecificaActionPerformed(evt);
            }
        });
        getContentPane().add(MascotaEspecifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, 220, 60));

        topMascotasPesadas.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        topMascotasPesadas.setForeground(new java.awt.Color(0, 102, 102));
        topMascotasPesadas.setText("Top mascotas pesadas");
        topMascotasPesadas.setContentAreaFilled(false);
        getContentPane().add(topMascotasPesadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 240, 60));

        topMascotasVacunadas.setText("Top mascotas vacunadas");
        topMascotasVacunadas.setContentAreaFilled(false);
        topMascotasVacunadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topMascotasVacunadasActionPerformed(evt);
            }
        });
        getContentPane().add(topMascotasVacunadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 250, 60));

        menuCerrarSesion.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        menuCerrarSesion.setText("CERRAR SESION");
        getContentPane().add(menuCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 150, -1));

        menuSalir.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        menuSalir.setText("SALIR");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        getContentPane().add(menuSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Top mascotas mas livianas");
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, 60));

        infoMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(infoMenu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, 210));

        jLabel1.setMaximumSize(new java.awt.Dimension(897, 551));
        jLabel1.setMinimumSize(new java.awt.Dimension(897, 551));
        jLabel1.setPreferredSize(new java.awt.Dimension(897, 551));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuConquistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConquistarActionPerformed
        // TODO add your handling code here:
        Mascotas mn = new Mascotas();
        mn.setIdMascota(200);
        Pesos pn = new Pesos();
        Vacunas vn = new Vacunas();
        //infoMenu.setText(mn.info()+pn.info()+vn.info());
        
    }//GEN-LAST:event_menuConquistarActionPerformed

    private void ModificarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarMascotaActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ModificarMascota m1 = new ModificarMascota();
        m1.setVisible(true);
    }//GEN-LAST:event_ModificarMascotaActionPerformed

    private void EliminarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarMascotaActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        EliminarMascota m1 = new EliminarMascota();
        m1.setVisible(true);
    }//GEN-LAST:event_EliminarMascotaActionPerformed

    private void InsertarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarMascotaActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        InsertarMascota m1 = new InsertarMascota();
        m1.setVisible(true);
    }//GEN-LAST:event_InsertarMascotaActionPerformed

    private void MascotaEspecificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MascotaEspecificaActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        consultaEspMascota m1 = new consultaEspMascota();
        m1.setVisible(true);
    }//GEN-LAST:event_MascotaEspecificaActionPerformed

    private void topMascotasVacunadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topMascotasVacunadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topMascotasVacunadasActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarMascota;
    private javax.swing.JButton InsertarMascota;
    private javax.swing.JButton MascotaEspecifica;
    private javax.swing.JButton ModificarMascota;
    private javax.swing.JTable infoMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menuCerrarSesion;
    private javax.swing.JButton menuConquistar;
    private javax.swing.JButton menuSalir;
    private javax.swing.JToggleButton topMascotasPesadas;
    private javax.swing.JButton topMascotasVacunadas;
    // End of variables declaration//GEN-END:variables
}
