/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.MascotaApp.vistas;

import es.medac.MascotaApp.controller.ConexionBD;
import es.medac.MascotaApp.controller.DMLMascotas;
import java.sql.Connection;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ModificarMascota extends javax.swing.JFrame {
     private Connection conexionBD;

    /**
     * Creates new form ModificarMascota
     */
    public ModificarMascota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        idMascotaModificar = new javax.swing.JTextField();
        idClienteModificar = new javax.swing.JTextField();
        vacunasModificar = new javax.swing.JTextField();
        pesoModificar = new javax.swing.JTextField();
        volverModificar = new javax.swing.JButton();
        aliasModificar = new javax.swing.JTextField();
        fechaPesadoModificar = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        fechaVacunaModificar = new com.toedter.calendar.JDateChooser();
        listaModificar = new javax.swing.JComboBox<>();
        modificarUno = new javax.swing.JButton();
        idMascota = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID MASCOTAS:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID CLIENTE:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PESO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ALIAS MASCOTAS:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("VACUNACIONES:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("FECHA DE VACUNA PROXIMA:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, 30));

        idMascotaModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMascotaModificarActionPerformed(evt);
            }
        });
        getContentPane().add(idMascotaModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 100, -1));
        getContentPane().add(idClienteModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 100, -1));
        getContentPane().add(vacunasModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 100, -1));
        getContentPane().add(pesoModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 100, -1));

        volverModificar.setBackground(new java.awt.Color(102, 102, 255));
        volverModificar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        volverModificar.setForeground(new java.awt.Color(255, 255, 255));
        volverModificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\icons8-cerrar-sesión-60.png")); // NOI18N
        volverModificar.setText("Volver");
        volverModificar.setContentAreaFilled(false);
        volverModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volverModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverModificarActionPerformed(evt);
            }
        });
        getContentPane().add(volverModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        aliasModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aliasModificarActionPerformed(evt);
            }
        });
        getContentPane().add(aliasModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 100, -1));
        getContentPane().add(fechaPesadoModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 120, 30));

        jLabel14.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("FECHA DE PESADO:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));
        getContentPane().add(fechaVacunaModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 120, 30));

        listaModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "idMascota", "idCliente", "AliasMascota", "Vacunas", "Peso", "FechaVacunado", "FechaPesado" }));
        getContentPane().add(listaModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        modificarUno.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\icons8-modificar-80.png")); // NOI18N
        modificarUno.setContentAreaFilled(false);
        modificarUno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarUnoActionPerformed(evt);
            }
        });
        getContentPane().add(modificarUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, 60));
        getContentPane().add(idMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 110, -1));

        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\icons8-cerrar-sesión-60.png")); // NOI18N
        jButton1.setText("SALIR");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 50));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel5.setText("Introduzca el id de la mascota que quiere modificar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\gato.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idMascotaModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMascotaModificarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idMascotaModificarActionPerformed

    private void aliasModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aliasModificarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_aliasModificarActionPerformed

    private void modificarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarUnoActionPerformed
        // TODO add your handling code here:
        DMLMascotas dm1 = new DMLMascotas();
        SimpleDateFormat formato = new SimpleDateFormat("dd/mm/yyyy");
        if(listaModificar.getSelectedItem().toString().equals("idMascota")){
            dm1.updateSpecific(Integer.parseInt(idMascota.getText()), "idMascota", Integer.parseInt(idMascotaModificar.getText()));
        }else if(listaModificar.getSelectedItem().toString().equals("idCliente")){
            dm1.updateSpecific(Integer.parseInt(idMascota.getText()), "idCliente", Integer.parseInt(idClienteModificar.getText()));
        }else if(listaModificar.getSelectedItem().toString().equals("AliasMascota")){
            dm1.updateSpecific(Integer.parseInt(idMascota.getText()), "aliasMascota", aliasModificar.getText());
        }else if(listaModificar.getSelectedItem().toString().equals("Vacunas")){
            dm1.updateSpecific(Integer.parseInt(idMascota.getText()), "vacunaciones", Integer.parseInt(vacunasModificar.getText()));
        }else if(listaModificar.getSelectedItem().toString().equals("Peso")){
            dm1.updateSpecific(Integer.parseInt(idMascota.getText()), "Peso", Double.parseDouble(pesoModificar.getText()));
        }else if(listaModificar.getSelectedItem().toString().equals("FechaVacunado")){
            long FN = fechaVacunaModificar.getDate().getTime();
            java.sql.Date sqlFecha = new java.sql.Date(FN);          
            dm1.updateSpecific(Integer.parseInt(idMascota.getText()), "fechaVacuna", sqlFecha);
        }
        else if(listaModificar.getSelectedItem().toString().equals("FechaPesado")){
            long FN = fechaPesadoModificar.getDate().getTime();
            java.sql.Date sqlFecha = new java.sql.Date(FN);          
            dm1.updateSpecific(Integer.parseInt(idMascota.getText()), "fechaPesado", sqlFecha);
        }
        JOptionPane.showMessageDialog(this, "Acaba de modificar una mascota");
    }//GEN-LAST:event_modificarUnoActionPerformed

    private void volverModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverModificarActionPerformed
        // TODO add your handling code here:
        setVisible (false);
        Menu m1 = new Menu();
        m1.setVisible(true);
    }//GEN-LAST:event_volverModificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarMascota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aliasModificar;
    private com.toedter.calendar.JDateChooser fechaPesadoModificar;
    private com.toedter.calendar.JDateChooser fechaVacunaModificar;
    private javax.swing.JTextField idClienteModificar;
    private javax.swing.JTextField idMascota;
    private javax.swing.JTextField idMascotaModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> listaModificar;
    private javax.swing.JButton modificarUno;
    private javax.swing.JTextField pesoModificar;
    private javax.swing.JTextField vacunasModificar;
    private javax.swing.JButton volverModificar;
    // End of variables declaration//GEN-END:variables
}
