/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.MascotaApp.vistas;

import es.medac.MascotaApp.controller.ConexionBD;
import es.medac.MascotaApp.controller.DMLClientes;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class RegistrarCliente extends javax.swing.JFrame {
private Connection  conexionBD;
    /**
     * Creates new form RegistrarCliente
     */
    public RegistrarCliente() {
        initComponents();
        conexionBD = new ConexionBD().getConexion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idCliente = new javax.swing.JTextField();
        primerApellidoCliente = new javax.swing.JTextField();
        cuentaBancoCliente = new javax.swing.JTextField();
        telefonoCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        registrarCliente = new javax.swing.JButton();
        modificarCliente = new javax.swing.JButton();
        eliminarCliente = new javax.swing.JButton();
        listaCliente = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(idCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 71, 20));

        primerApellidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primerApellidoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(primerApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 71, -1));
        getContentPane().add(cuentaBancoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 80, -1));
        getContentPane().add(telefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 80, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setText("PRIMER APELLIDO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, 20));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel1.setText("ID CLIENTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 80, 20));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel3.setText("CUENTA DE BANCO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel4.setText("TELEFONO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 70, 20));

        registrarCliente.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        registrarCliente.setForeground(new java.awt.Color(0, 153, 153));
        registrarCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\icons8-registro-80.png")); // NOI18N
        registrarCliente.setText("REGISTRAR CLIENTE");
        registrarCliente.setContentAreaFilled(false);
        registrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(registrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 60));

        modificarCliente.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        modificarCliente.setForeground(new java.awt.Color(0, 153, 153));
        modificarCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\icons8-modificar-80.png")); // NOI18N
        modificarCliente.setText("MODIFICAR CLIENTE");
        modificarCliente.setContentAreaFilled(false);
        modificarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(modificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 60));

        eliminarCliente.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        eliminarCliente.setForeground(new java.awt.Color(0, 153, 153));
        eliminarCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\icons8-eliminar-80.png")); // NOI18N
        eliminarCliente.setText("ELIMINAR CLIENTE");
        eliminarCliente.setContentAreaFilled(false);
        eliminarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, 60));

        listaCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Cliente\t", "Primer apellido", "Cuenta de banco", "Numero Telefonico" }));
        getContentPane().add(listaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Introduce los datos del cliente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\icons8-cerrar-sesión-60.png")); // NOI18N
        jButton1.setText("VOLVER");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, -1, 50));

        jButton2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\icons8-cerrar-ventana-60.png")); // NOI18N
        jButton2.setText("SALIR");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, -1, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\dog-5960092_640.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 570, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarClienteActionPerformed
        // TODO add your handling code here:
        DMLClientes dm1 = new DMLClientes();
        dm1.insertAll(Integer.parseInt(idCliente.getText()), primerApellidoCliente.getText(), 
                cuentaBancoCliente.getText(), Integer.parseInt(telefonoCliente.getText()));
        JOptionPane.showMessageDialog(this, "Cliente registrado");
    }//GEN-LAST:event_registrarClienteActionPerformed

    private void modificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarClienteActionPerformed
        // TODO add your handling code here:
        DMLClientes dm1 = new DMLClientes();
        if(listaCliente.getSelectedItem().toString().equals("ID Cliente")){
            dm1.updateSpecific(Integer.parseInt(idCliente.getText()), "idCliente", Integer.parseInt(idCliente.getText()));
        }else if(listaCliente.getSelectedItem().toString().equals("Primer apellido")){
            dm1.updateSpecific(Integer.parseInt(idCliente.getText()), "primerApellido", primerApellidoCliente.getText());
        }else if(listaCliente.getSelectedItem().toString().equals("Cuenta de banco")){
            dm1.updateSpecific(Integer.parseInt(idCliente.getText()), "cuentaBanco", cuentaBancoCliente.getText());
        }else if(listaCliente.getSelectedItem().toString().equals("Numero Telefonico")){
            dm1.updateSpecific(Integer.parseInt(idCliente.getText()), "telefono", telefonoCliente.getText());
        }
                JOptionPane.showMessageDialog(this, "Cliente modificado");
       
    }//GEN-LAST:event_modificarClienteActionPerformed

    private void eliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClienteActionPerformed
        // TODO add your handling code here:
        DMLClientes dm1 = new DMLClientes();
        dm1.deleteid(Integer.parseInt(idCliente.getText()));
                JOptionPane.showMessageDialog(this, "Cliente eliminado");

    }//GEN-LAST:event_eliminarClienteActionPerformed

    private void primerApellidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primerApellidoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primerApellidoClienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible (false);
        InsertarMascota r1 = new InsertarMascota();
        r1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cuentaBancoCliente;
    private javax.swing.JButton eliminarCliente;
    private javax.swing.JTextField idCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> listaCliente;
    private javax.swing.JButton modificarCliente;
    private javax.swing.JTextField primerApellidoCliente;
    private javax.swing.JButton registrarCliente;
    private javax.swing.JTextField telefonoCliente;
    // End of variables declaration//GEN-END:variables
}
